//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave_From_ProSoft.View.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_fr_FR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_fr_FR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave_From_ProSoft.Utils.Language.Lang.fr-FR", typeof(Lang_fr_FR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour au menu principal.
        /// </summary>
        internal static string BackToMainMenu {
            get {
                return ResourceManager.GetString("BackToMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retourner au menu principal et ne rien faire.
        /// </summary>
        internal static string BackToMainMenuAndDoNothing {
            get {
                return ResourceManager.GetString("BackToMainMenuAndDoNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes vous sûr de vouloir réinitialiser cette action ? (Toutes les options relatives à l&apos;action seront supprimées).
        /// </summary>
        internal static string ConfirmReset {
            get {
                return ResourceManager.GetString("ConfirmReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer une sauvegarde.
        /// </summary>
        internal static string CreateBackup {
            get {
                return ResourceManager.GetString("CreateBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer une nouvelle action de sauvegarde.
        /// </summary>
        internal static string CreateNewJob {
            get {
                return ResourceManager.GetString("CreateNewJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dossier actuel.
        /// </summary>
        internal static string CurrentFolder {
            get {
                return ResourceManager.GetString("CurrentFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Définir le mode de sauvegarde.
        /// </summary>
        internal static string DefineSaveMode {
            get {
                return ResourceManager.GetString("DefineSaveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Définir le chemin de source.
        /// </summary>
        internal static string DefineSourcePath {
            get {
                return ResourceManager.GetString("DefineSourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Définir le chemin cible.
        /// </summary>
        internal static string DefineTargetPath {
            get {
                return ResourceManager.GetString("DefineTargetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarde Differentielle.
        /// </summary>
        internal static string DifferentialBackup {
            get {
                return ResourceManager.GetString("DifferentialBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer le nom de la nouvelle action.
        /// </summary>
        internal static string EnterJobName {
            get {
                return ResourceManager.GetString("EnterJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitter.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarde completes.
        /// </summary>
        internal static string FullBackup {
            get {
                return ResourceManager.GetString("FullBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options d&apos;action de sauvegarde.
        /// </summary>
        internal static string JobOptions {
            get {
                return ResourceManager.GetString("JobOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [grey](Appuez sur [blue]&lt;espace&gt;[/] pour selectionner une action, [green]&lt;entrer&gt;[/] pour executer les actions séléctionnées)[/].
        /// </summary>
        internal static string JobsListIndication {
            get {
                return ResourceManager.GetString("JobsListIndication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez choisi.
        /// </summary>
        internal static string LanguageSelected {
            get {
                return ResourceManager.GetString("LanguageSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemin d&apos;accès aux logs.
        /// </summary>
        internal static string LogPath {
            get {
                return ResourceManager.GetString("LogPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Principal.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu des options.
        /// </summary>
        internal static string OptionsMenu {
            get {
                return ResourceManager.GetString("OptionsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appuyez sur une touche pour continuer.
        /// </summary>
        internal static string PressAKeyToContinue {
            get {
                return ResourceManager.GetString("PressAKeyToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renommer l&apos;action de sauvegarde.
        /// </summary>
        internal static string RenameJob {
            get {
                return ResourceManager.GetString("RenameJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialiser cette action /!\.
        /// </summary>
        internal static string ResetJob {
            get {
                return ResourceManager.GetString("ResetJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectionner une action de sauvegarde.
        /// </summary>
        internal static string SelectJob {
            get {
                return ResourceManager.GetString("SelectJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez une action.
        /// </summary>
        internal static string SelectJobPrompt {
            get {
                return ResourceManager.GetString("SelectJobPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez la langue.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executer plusieurs actions de sauvegarde.
        /// </summary>
        internal static string SelectMultipleJobs {
            get {
                return ResourceManager.GetString("SelectMultipleJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemin d&apos;accès aux Status.
        /// </summary>
        internal static string StatusPath {
            get {
                return ResourceManager.GetString("StatusPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarde effctuée avec succès.
        /// </summary>
        internal static string SuccessfullBackup {
            get {
                return ResourceManager.GetString("SuccessfullBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilise ce dossier.
        /// </summary>
        internal static string ValidateFolder {
            get {
                return ResourceManager.GetString("ValidateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quels [green]actions[/] voulez vous executer?.
        /// </summary>
        internal static string WhatJobsList {
            get {
                return ResourceManager.GetString("WhatJobsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
